### ISSUE TITLE
Речник

### ISSUE THREAD

**Issue by bkaradzic** [stalker314314/b92statistike#1]
Да ли база садржи комплетан речник са фреквенцијом речи коришћених у текстовима вести?

**Comment by bkaradzic** [comment]
Успео сам да скинем бекап. Видим има целе текстове и коментаре. Да ли је ово могуће прочити са неким опен сорс софтвером? Наиме, ако могу да извучем текст могу сам да направим парсер који ће произвести речник који ми треба.

**Comment by stalker314314** [comment]
Da, mozes da citas sa bilo kojim softverom ove reci - samo se nakacis na bazu. Ako pogledas, imas program title_word_statistics.py koji ima prost regex parser da razdeli naslov vesti na reci. To mozes da uzmes kao osnovu

**Comment by vlada5** [comment]
da li previdjam ali... koji je user i password za logovanje na masinu?

**Comment by stalker314314** [comment]
Pitas za .bacpac fajl, @vlada5 ? Ako za njega pitas, on je sada ovde https://kokanbackups.blob.core.windows.net/db-bacpacs/b92-2016-1-18-22-29.bacpac (user: sef, pass: N0vakovic)

**Comment by vlada5** [comment]
Koji su kredencijali za ulaz na ubuntu u opciji "Hoću sve od nule"?

**Comment by stalker314314** [comment]
Hm, nema tu nista specificno, obican vagrant. Jel ti radi bilo kakav Vagrant? Ako koristis Windows, pogledaj ovde: https://docs-v1.vagrantup.com/v1/docs/getting-started/ssh.html
